INSERT INTO PERSON (ID, IS_AFFILIATE, FIRST_NAME, LAST_NAME) Values (NEXTVAL('HIBERNATE_SEQUENCE'),FALSE, 'Abdullah', 'Rahim');
INSERT INTO PERSON (ID, IS_AFFILIATE, FIRST_NAME, LAST_NAME) Values (NEXTVAL('HIBERNATE_SEQUENCE'),TRUE, 'Zohair', 'Atique');
INSERT INTO PERSON (ID, IS_AFFILIATE, FIRST_NAME, LAST_NAME) Values (NEXTVAL('HIBERNATE_SEQUENCE'),FALSE, 'Adil', 'Abbasi');
INSERT INTO PERSON (ID, IS_AFFILIATE, FIRST_NAME, LAST_NAME) Values (NEXTVAL('HIBERNATE_SEQUENCE'),FALSE, 'Taimoor', 'Liaqat');

INSERT INTO CUSTOMER (ID,PERSON_ID ,FIRST_ORDER ,LAST_ORDER ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 1, '2019-01-01', NOW());
INSERT INTO CUSTOMER (ID,PERSON_ID ,FIRST_ORDER ,LAST_ORDER ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 2, '2019-01-01', NOW());
INSERT INTO CUSTOMER (ID,PERSON_ID ,FIRST_ORDER ,LAST_ORDER ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 3, '2016-01-01', NOW());
INSERT INTO CUSTOMER (ID,PERSON_ID ,FIRST_ORDER ,LAST_ORDER ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 4, '2019-01-01', NOW());

INSERT INTO EMPLOYEE  (ID,PERSON_ID) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 1);

INSERT INTO PRODUCT   (ID, NAME, PRICE , PRODUCT_TYPE ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'Rice', 105, 'GROCERY');
INSERT INTO PRODUCT   (ID, NAME, PRICE , PRODUCT_TYPE ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'Wheat', 110, 'GROCERY');
INSERT INTO PRODUCT   (ID, NAME, PRICE , PRODUCT_TYPE ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'Head Phone', 200, 'OTHER');
INSERT INTO PRODUCT   (ID, NAME, PRICE , PRODUCT_TYPE ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'Mobile Cover', 150, 'OTHER');


